# Generated by Django 5.1.3 on 2024-12-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.jpg", upload_to="profile_images"),
        ),
    ]
